#!/usr/bin/env bash
#script that stops 4-to_infinity_and_beyond process using kill
process_pid=$(pgrep -f "4-to_infinity_and_beyond")
if [ -n "$process_pid" ]; then
  kill "$process_pid"
else
  echo "Process is not running."
fi
